site_name: pyGenomeViz
site_description: A genome visualization python package for comparative genomics
site_url: https://github.com/moshi4/pyGenomeViz
repo_name: moshi4/pyGenomeViz
repo_url: https://github.com/moshi4/pyGenomeViz

nav:
  - Home: index.md
  - API Docs:
      - GenomeViz: api-docs/genomeviz.md
      - FeatureTrack: api-docs/track.md
      - Genbank: api-docs/genbank.md
  - Usage Examples:
      - Basic Usage: usage-examples/basic_usage.ipynb
      - Practical Usage: usage-examples/practical_usage.ipynb
      - Customization Tips: usage-examples/customization_tips.ipynb

theme:
    name: material # material, readthedocs
    features:
      - navigation.top
      - navigation.expand
      - navigation.tabs
      - navigation.tabs.sticky
      # - navigation.sections

plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        handlers:
          python:
            # Reference: https://mkdocstrings.github.io/python/usage/
            options:
              # Heading options
              heading_level: 2
              # Member options
              members_order: source # alphabetical, source
              # Docstrings options
              docstring_style: numpy
              docstring_section_style: table # table, list, spacy
              merge_init_into_class: True
              # Additional options
              show_source: False
