site_name: pyGenomeViz
site_description: A genome visualization python package for comparative genomics
site_author: moshi4
repo_name: moshi4/pyGenomeViz
repo_url: https://github.com/moshi4/pyGenomeViz
edit_uri: ''
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started: getting_started.ipynb
  - Examples:
      - Basic Example: examples/basic_example.ipynb
      - Practical Example: examples/practical_example.ipynb
      - Gallery Example: examples/gallery_example.ipynb
      - Customization Tips: examples/customization_tips.ipynb
  - API Docs:
      - GenomeViz: api-docs/genomeviz.md
      - FeatureTrack: api-docs/track.md
      - Genbank: api-docs/genbank.md

theme:
    name: material # material, readthedocs
    features:
      - navigation.top
      - navigation.expand
      # - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        handlers:
          python:
            # Reference: https://mkdocstrings.github.io/python/usage/
            options:
              # Heading options
              heading_level: 2
              # Member options
              members_order: source # alphabetical, source
              # Docstrings options
              docstring_style: numpy
              docstring_section_style: table # table, list, spacy
              merge_init_into_class: True
              # Additional options
              show_source: False
