site_name: pyGenomeViz
site_description: A genome visualization python package for comparative genomics
site_author: moshi4
repo_name: moshi4/pyGenomeViz
repo_url: https://github.com/moshi4/pyGenomeViz
edit_uri: ''
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started: getting_started.ipynb
  - API Examples:
      - Basic Example: api-examples/basic_example.ipynb
      - Practical Example: api-examples/practical_example.ipynb
      - Customization Tips: api-examples/customization_tips.ipynb
      - Gallery Example: api-examples/gallery_example.ipynb
  - API Docs:
      - GenomeViz: api-docs/genomeviz.md
      - FeatureTrack: api-docs/track.md
      - Genbank: api-docs/genbank.md
  - CLI Docs:
      - pgv-simpleplot: cli-docs/pgv-simpleplot.md
      - pgv-mummer: cli-docs/pgv-mummer.md
      - pgv-mmseqs: cli-docs/pgv-mmseqs.md
      - pgv-pmauve: cli-docs/pgv-pmauve.md

theme:
    name: material # material, readthedocs
    features:
      - navigation.top
      - navigation.expand
      # - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html

plugins:
    - search
    - mkdocs-jupyter:
        execute: False
    - mkdocstrings:
        handlers:
          python:
            # Reference: https://mkdocstrings.github.io/python/usage/
            options:
              # Heading options
              heading_level: 2
              # Member options
              members_order: source # alphabetical, source
              # Docstrings options
              docstring_style: numpy
              docstring_section_style: table # table, list, spacy
              merge_init_into_class: True
              # Additional options
              show_source: False
