site_name: pyGenomeViz
site_description: A genome visualization python package for comparative genomics
site_author: moshi4
repo_name: moshi4/pyGenomeViz
repo_url: https://github.com/moshi4/pyGenomeViz
edit_uri: ""
use_directory_urls: true
watch:
  - src

nav:
  - Home: index.md
  - Getting Started: getting_started.ipynb
  - Example Gallery: example_gallery.ipynb
  - Plot Tips: plot_tips.ipynb
  - API Docs:
      - GenomeViz: api-docs/genomeviz.md
      - FeatureTrack: api-docs/track.md
      - FeatureSegment: api-docs/segment.md
      - Genbank: api-docs/genbank.md
      - Gff: api-docs/gff.md
      - utils: api-docs/utils.md
  - CLI Docs:
      - pgv-blast: cli-docs/pgv-blast.md
      - pgv-mummer: cli-docs/pgv-mummer.md
      - pgv-mmseqs: cli-docs/pgv-mmseqs.md
      - pgv-pmauve: cli-docs/pgv-pmauve.md
  - GUI Docs:
      - pgv-gui: gui-docs/pgv-gui.md

theme:
  name: material # material, readthedocs, mkdocs
  features:
    - navigation.top
    - navigation.expand
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
  - mkdocstrings:
      handlers:
        python:
          # Reference: https://mkdocstrings.github.io/python/usage/
          options:
            # Heading options
            heading_level: 2
            show_root_full_path: False
            show_root_heading: True
            # Member options
            members_order: source # alphabetical, source
            # Docstrings options
            docstring_style: numpy
            docstring_section_style: spacy # table, list, spacy
            line_length: 89
            merge_init_into_class: True
            # Signatures/annotations options
            show_signature_annotations: True
            separate_signature: True
            # Additional options
            show_source: False
