name: Publish MkDocs

on:
  push:
    branches: [main]
    paths: ["src/**.py", "docs/**","mkdocs.yml"]
  workflow_dispatch:

jobs:
  publish_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install MkDocs & Plugins
        run: pip install mkdocs mkdocs-material mkdocs-jupyter mkdocstrings[python]

      - name: Publish document
        run: mkdocs gh-deploy --force
