name: Publish MkDocs

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs & Plugins
        run: |
          pip install .
          pip install mkdocs mkdocs-material mkdocs-jupyter mkdocstrings[python] black

      - name: Publish document
        run: mkdocs gh-deploy --force
