name: Publish to PyPI
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    env:
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
