name: Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Target version

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pygenomeviz:latest
            ghcr.io/${{ github.repository_owner }}/pygenomeviz:v${{ github.event.inputs.version }}
