name: Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Target version

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build --tag ghcr.io/$GITHUB_ACTOR/pygenomeviz:v${{ github.event.inputs.version }} .

      - name: Docker Push
        run: docker push ghcr.io/$GITHUB_ACTOR/pygenomeviz:v${{ github.event.inputs.version }}
